apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedemo-api
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      name: kubedemo-api
  template:
    metadata:
      labels:
        name: kubedemo-api
    spec:
      containers:
      - name: kubedemo-api
        image: asia.gcr.io/albedo-157516/kubedemo-api:v1
        envFrom:
        - configMapRef:
            name: kubedemo-api
        ports:
        - name: kubedemo-api
          containerPort: 8000
        resources:
          requests:
            cpu: "1000m"
            memory: "1000Mi"
          limits:
            cpu: "1000m"
            memory: "1000Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
