kind: Service
apiVersion: v1
metadata:
  name: simple-frontend
  labels:
    app: simple-frontend
spec:
  type: NodePort
  selector:
    app: simple-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 80
      protocol: TCP
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: simple-frontend
  labels:
    app: simple-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-frontend
  template:
    metadata:
      labels:
        app: simple-frontend
      annotations:
        author: https://github.com/vinta
    spec:
      containers:
      - name: simple-frontend
        # image: IMAGE_NAME
        image: asia.gcr.io/simple-project-198818/simple-frontend:v1
        ports:
          - name: http
            containerPort: 80
        resources:
          requests:
            cpu: "0.1"
            memory: "0.1G"
          limits:
            cpu: "1"
            memory: "1G"
        livenessProbe:
          httpGet:
            path: /
            port: 80
