kind: Deployment
apiVersion: apps/v1
metadata:
  name: kubedemo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      name: kubedemo-api
  template:
    metadata:
      labels:
        name: kubedemo-api
        app: flask
      annotations:
        author: vinta
    spec:
      containers:
      - name: kubedemo-api
        image: asia.gcr.io/albedo-157516/kubedemo-api:v1
        envFrom:
        - configMapRef:
            name: kubedemo-api
        ports:
        - name: http
          containerPort: 8000
        resources:
          requests:
            cpu: 1
            memory: 1G
          limits:
            cpu: 2
            memory: 2G
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
