kind: Service
apiVersion: v1
metadata:
  name: kubedemo-api
  labels:
    app: kubedemo-api
spec:
  type: NodePort
  selector:
    app: kubedemo-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
    - name: https
      port: 443
      targetPort: 8000
      protocol: TCP
