kind: Deployment
apiVersion: apps/v1
metadata:
  name: simple-frontend
  labels:
    app: simple-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-frontend
  template:
    metadata:
      labels:
        app: simple-frontend
    spec:
      containers:
      - name: simple-frontend
        image: asia.gcr.io/albedo-157516/simple-frontend
        ports:
          - name: http
            containerPort: 80
