kind: Service
apiVersion: v1
metadata:
  name: simple-api
  labels:
    app: simple-api
spec:
  type: NodePort
  selector:
    app: simple-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
    - name: https
      port: 443
      targetPort: 8000
      protocol: TCP
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: simple-api
  labels:
    app: simple-api
data:
  MONGODB_URL: mongodb://mongodb.default.svc.cluster.local/simple-project
  REDIS_CACHE_URL: redis://redis-cache.default.svc.cluster.local/0
  REDIS_QUEUE_URL: redis://redis-queue.default.svc.cluster.local/0
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: simple-api
  labels:
    app: simple-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-api
  template:
    metadata:
      labels:
        app: simple-api
      annotations:
        author: https://github.com/vinta
    spec:
      containers:
      - name: simple-api
        image: IMAGE_NAME
        envFrom:
        - configMapRef:
            name: simple-api
        ports:
        - name: http
          containerPort: 8000
        resources:
          requests:
            cpu: "0.1"
            memory: "0.1G"
          limits:
            cpu: "1"
            memory: "1G"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
