apiVersion: skaffold/v1alpha1
kind: Config
build:
  artifacts:
  - imageName: asia.gcr.io/simple-project-198818/simple-frontend
    workspace: .
  local: {}
deploy:
  kubectl:
    manifests:
    - paths:
      - ../infrastructure/simple-frontend/*
      parameters:
        IMAGE_NAME: asia.gcr.io/simple-project-198818/simple-frontend
